CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  description TEXT NULL,
  hsn VARCHAR(50) NULL,
  unit VARCHAR(50) NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  gst_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quote_no VARCHAR(50) NULL,
  quote_date DATE NOT NULL,
  customer_name VARCHAR(200) NOT NULL,
  customer_phone VARCHAR(50) NULL,
  customer_email VARCHAR(120) NULL,
  customer_address TEXT NULL,
  customer_gstin VARCHAR(50) NULL,
  proposal_items_json LONGTEXT NULL,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  cgst_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  sgst_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quote_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quote_id INT NOT NULL,
  product_id INT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT NULL,
  hsn VARCHAR(50) NULL,
  unit VARCHAR(50) NULL,
  qty DECIMAL(12,2) NOT NULL DEFAULT 0,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  gst_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
  taxable DECIMAL(12,2) NOT NULL DEFAULT 0,
  cgst DECIMAL(12,2) NOT NULL DEFAULT 0,
  sgst DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_quote_items_quote
    FOREIGN KEY (quote_id)
    REFERENCES quotes(id)
    ON DELETE CASCADE
);
